### ISSUE TITLE
Update `wget` from L105 of the action to be universal.

### ISSUE THREAD

**Issue by Virus5600** [headlesshq/mc-runtime-test#57]
I'm testing on both Ubuntu and Windows for my actions but it kept failing at [Lines 102 - 107](https://github.com/headlesshq/mc-runtime-test/blob/main/action.yml#L102-L107) due to `wget` only available when the OS is set to Ubuntu.

![image](https://github.com/user-attachments/assets/9f5c69eb-5091-4c49-93f0-617d9fe8d9ab)

A quick fix of having a conditional step for this or using [suisei-cn/actions-download-file](https://github.com/suisei-cn/actions-download-file) workflow can be applied to prevent such errors.

This line would suffice for the latter option:
```yml
    - name: Download fabric-api v${{ inputs.fabric-api }}
      uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9
      with:
        url: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/${{ inputs.fabric-api }}+${{ inputs.mc }}/fabric-api-${{ inputs.fabric-api }}+${{ inputs.mc }}.jar
        target: "run/mods"
```
